version: '3.8'

services:
  # MariaDB Database Service
  db:
    image: mysql:8.0
    container_name: facturatie_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - facturatie_network

  # FossBilling Application Service
  app:
    image: fossbilling/fossbilling:latest
    container_name: facturatie_app
    depends_on:
      - db
    ports:
      - "30081:80"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - app_data:/var/www/html
    networks:
      - facturatie_network

  # phpMyAdmin Service (for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: facturatie_phpmyadmin
    depends_on:
      - db
    ports:
      - "30082:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - facturatie_network

  # NEW: User Creation Listener Service
  user-listener:
    build: ./user-creation-listener
    container_name: facturatie_user_listener
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    networks:
      - facturatie_network

networks:
  facturatie_network:
    driver: bridge

volumes:
  db_data:
  app_data: