name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: /home/ehbstudent/facturatie 

      - name: Load environment variables
        run: |
          # Copy .env file from repository to working directory
          cp .env /home/ehbstudent/facturatie/.env || true
          echo "Environment file prepared"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        if: github.ref == 'refs/heads/development'
        working-directory: /home/ehbstudent/facturatie
        run: |
          docker compose down || true
          docker compose up --build -d
          sleep 10  # Wait for services to initialize
          docker compose restart  # Ensure fresh start

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest
          for module in */requirements.txt; do
            pip install -r "$module"
          done

      - name: Run tests
        run: |
          pytest */test_*.py

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
