name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers
        if: github.ref == 'refs/heads/development'
        run: |
          docker-compose up --build -d
  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.2'

      - name: Install module dependencies
        run: |
          # Install requirements for each module
          pip install -r user-creation-providor/requirements.txt
          pip install -r user-creation-consumer/requirements.txt
          pip install -r user-update-providor/requirements.txt
          pip install -r user-update-consumer/requirements.txt
          pip install -r user-deletion-providor/requirements.txt
          pip install -r user-deletion-consumer/requirements.txt
      - name: Run tests
        run: |
          python -m unittest user-creation-providor/test_creation_providor.py
          python -m unittest user-creation-consumer/test_creation_consumer.py
          python -m unittest user-update-providor/test_update_providor.py
          python -m unittest user-update-consumer/test_update_consumer.py
          python -m unittest user-deletion-providor/test_deletion_providor.py
          python -m unittest user-deletion-consumer/test_deletion_consumer.py
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to main
        run: |
          # Add your deployment commands here
          echo "Deploying to main..."
