name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker containers
        if: github.ref == 'refs/heads/development'
        run: |
          docker compose up --build -d

  test:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest
          # Install requirements for all modules
          for module in user-creation-providor user-creation-consumer \
                       user-update-providor user-update-consumer \
                       user-deletion-providor user-deletion-consumer; do
            if [ -f "$module/requirements.txt" ]; then
              pip install -r "$module/requirements.txt"
            fi
          done

      - name: Run tests
        run: |
          # Run tests for all modules
          pytest user-creation-providor/test_creation_providor.py \
                user-creation-consumer/test_creation_consumer.py \
                user-update-providor/test_update_providor.py \
                user-update-consumer/test_update_consumer.py \
                user-deletion-providor/test_deletion_providor.py \
                user-deletion-consumer/test_deletion_consumer.py

      - name: Verify test results
        if: ${{ always() }}
        run: |
          echo "Test execution completed"
          # Add any additional verification steps here

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && success()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to main
        run: |
          echo "Deploying to main..."
          # Add your actual deployment commands here
