name: Main Branch Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create full .env file
        run: |
          cat << EOF > .env
          RABBITMQ_HOST=${{ secrets.RABBITMQ_HOST }}
          RABBITMQ_PORT=${{ secrets.RABBITMQ_PORT }}
          RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          EOF

      - name: Run tests
        run: |
          set +e
          docker compose exec -T user-creation-providor pytest test_creation_providor.py || echo "Creation provider tests failed"
          docker compose exec -T user-creation-consumer pytest test_creation_consumer.py || echo "Creation consumer tests failed"
          docker compose exec -T user-update-providor pytest test_update_providor.py || echo "Update provider tests failed"
          docker compose exec -T user-update-consumer pytest test_update_consumer.py || echo "Update consumer tests failed"
          docker compose exec -T user-deletion-providor pytest test_deletion_providor.py || echo "Deletion provider tests failed"
          docker compose exec -T user-deletion-consumer pytest test_deletion_consumer.py || echo "Deletion consumer tests failed"
          exit 0
